os:
  - linux
  - osx

osx_image: xcode10.2
language: node_js
node_js: "12"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

stages:
  - test
  - env
  - name: deploy
    if: branch = develop

env:
  - SKIP_PREFLIGHT_CHECK=true
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: test
      os: osx
      install:
        - yarn
      script:
        - npm run validate
        - yarn danger ci
    - stage: env
      os: osx
      install:
        - yarn
      script:
        - npm run build
    - stage: deploy
      install:
        - yarn
      script:
        - echo "Deploying to Github"
      before_deploy:
        - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x add-osx-cert.sh; fi
        - if [ "$TRAVIS_OS_NAME" = osx ]; then ./add-osx-cert.sh; fi
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
      deploy:
        provider: script
        cleanup: false
        script: npx semantic-release
