language: node_js
node_js:
  - 12
dist: trusty
sudo: false

branches:
  only:
    - master
    - develop
    - 2.0

stages:
  - test
  - env
  - name: deploy
    if: branch = master

env:
  - SKIP_PREFLIGHT_CHECK=true

jobs:
  include:
    - stage: test
      install:
        - yarn
      script:
        - npm run validate
        - yarn danger ci
    - stage: env
      install:
        - yarn
      script:
        - npm run build
    - stage: deploy
      install:
        - yarn
      script:
        - echo "Deploying to Github"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
