language: node_js
node_js:
  - 10
dist: trusty
sudo: false

branches:
  only:
    - master
    - develop
    - 2.0

stages:
  - test
  - env
  - name: deploy
    if: branch = master

env:
  - SKIP_PREFLIGHT_CHECK=true

install:
  - npm install
script:
  - npm run validate -- --forceExit
  - yarn danger ci

jobs:
  include:
    - stage: env
      install:
        - npm install
      script:
        - npm run build
    - stage: deploy
      install:
        - npm install
      script:
        - echo "Deploying to Github"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
