os: osx
osx_image: xcode10.2
language: node_js
node_js: "12"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

stages:
  - test
  - environment
  - name: deploy
    # if: branch = develop

jobs:
  include:
    # - stage: test
    #   env: SKIP_PREFLIGHT_CHECK=true
    #   install:
    #     - yarn
    #   script:
    #     - npm run validate
    #     - yarn danger ci
    - stage: environment
      env: SKIP_PREFLIGHT_CHECK=true
      install:
        - yarn
      script:
        - npm run build
    - stage: deploy
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - SKIP_PREFLIGHT_CHECK=true
      install:
        - yarn
      script:
        - ls
      before_deploy:
        - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x scripts/add-osx-cert.sh;
          fi
        - if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/add-osx-cert.sh; fi
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
      deploy:
        provider: script
        skip_cleanup: true
        script: travis_wait npx semantic-release
        on:
          branch: develop
