language: node_js
node_js:
  - 10
dist: trusty
sudo: false

branches:
  only:
    - master
    - develop
    - 2.0

stages:
  - test
  - env
  - name: deploy
    if: branch = master

install:
  - npm install
script:
  - npm run validate -- --forceExit
  - yarn danger ci

jobs:
  include:
    - stage: env
      install:
        - npm install
      script:
        - npm run mk-build && npm run build-env && cat ./build/.env
    - stage: deploy
      install:
        - npm install
        - npm install --prefix client
        - npm install --prefix server
      script:
        - echo "Deploying to Github"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
